### ISSUE TITLE
Support for cocoapods

### ISSUE THREAD

**Issue by nosadaniel** [Loupehope/PasswordChecker#4]
Is there a way to add this library with cocoapods to iOS without using swift package manager?

**Comment by Loupehope** [comment]
Hello! Thank you very much for your interest in the project. Added support for cocoapods from project version 1.4.0

**Comment by nosadaniel** [comment]
thank @Loupehope for quickly adding this.
Would it be possible to publish to this library on cocoapods? 
I think, it would be easy for other developers to use by simply doing ```pod PasswordChecker ```

**Comment by Loupehope** [comment]
The library is already available for installation via `pod 'PasswordChecker'`. To be on the safe side, run `pod install --repo-update`.
